"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var authentication_js_1 = require("../auth/authentication.js");
var admin_js_1 = require("../controllers/admin.js");
var router = express_1.default.Router();
router.get('/serverStatus', admin_js_1.getServerStatus);
router.post('/openServer', authentication_js_1.loggedInAsAdmin, admin_js_1.openRaceServer);
router.post('/closeServer', authentication_js_1.loggedInAsAdmin, admin_js_1.closeRaceServer);
router.post('/newHorses', authentication_js_1.loggedInAsAdmin, admin_js_1.purgeHorses);
exports.default = router;
