"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var users_js_1 = require("../controllers/users.js");
var authentication_js_1 = require("../auth/authentication.js");
var router = express_1.default.Router();
router.get('/', users_js_1.getAllUsers);
router.get('/:uname', users_js_1.getUserByUsername);
router.delete('/:uname', authentication_js_1.loggedInAsAdmin, users_js_1.deleteUser);
exports.default = router;
